# Generated by Django 5.1.2 on 2024-10-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='file',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
